### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by lillelilje** [oleerik/pyplanemode#2]
Better icon is needed...
https://www.iconfinder.com/icons/59201/fly_plane_icon#size=32 maybe?

**Comment by rsmaior** [comment]
I tested here and did one screenshot http://pasteboard.co/rkgE89R.png

I think it's a good one, but it has a white curve simulating a shadow. If we change the colours it can lose the shadow?

Question: Maybe it's better to use an svg? (it doesn't lose quality when resized, so it'll adapt to diferent monitor resolutions)

I found a big list in wikipedia here https://commons.wikimedia.org/wiki/Category:Aircraft_icons (it has lots of png's and svg's plus licensing information)

**Comment by lillelilje** [comment]
ah awesome. And yes, using a svg would be better I guess!

I can change the colours - that much I can do :)

Any of them that you like a lot?

**Comment by lillelilje** [comment]
I really like this one actually: https://commons.wikimedia.org/wiki/Category:Aircraft_icons#/media/File:Aiga_departingflights_inv.svg

Easy enough to change the colours on it.

What do you think?

**Comment by rsmaior** [comment]
Tried this one https://upload.wikimedia.org/wikipedia/commons/b/b4/Aiga_departingflights.svg

The licensing is:
--This work has been released into the public domain by its author, I, Sopoforic. This applies worldwide.
--In some countries this may not be legally possible; if so:
--I, Sopoforic grants anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.
Source: https://commons.wikimedia.org/wiki/File:Aiga_departingflights.svg

The image is already svg and 45 degree rotated. I opened it in inkscape and put 60 60 60 in RGB to get a dark grey and 255 123 0 to get an orange colour. It gets good

**Comment by lillelilje** [comment]
Ooh, if it works well just submit a pull request :)

**Comment by rsmaior** [comment]
Well, I tried with you image. But I think it's better without the background. The image I selected is just the plane (simpler). I edited it and saved into two files.

By 'pull request' you mean attaching the files?

**Comment by lillelilje** [comment]
Ah, I might have misunderstood you. I thought you tried the one you linked last aswell (including changing it's colours?)
If you did you can clone the git repo, replace the icons and push. That would generate a pull request that I have to accept for your changes to take effect, I believe?

haven't really used git much so please correct me if I'm wrong.

**Comment by rsmaior** [comment]
I never did a pull request, I just use this account for reporting bugs. But I will try to follow the steps you described.

**Comment by lillelilje** [comment]
If it's easier you can just attach the files and I'll implement them. Doesn't really matter who does what! :)

**Comment by rsmaior** [comment]
Tried with email and username but failed:

rodrigo@3217 ~/pyplanemode $ git push origin master
Username for 'https://github.com': rudregues
Password for 'https://rudregues@github.com': 
remote: Permission to oleerik/pyplanemode.git denied to rudregues.
fatal: unable to access 'https://github.com/oleerik/pyplanemode/': The requested URL returned error: 403

rodrigo@3217 ~/pyplanemode $ git push origin master
Username for 'https://github.com': iquequeisso@gmail.com
Password for 'https://iquequeisso@gmail.com@github.com': 
remote: Permission to oleerik/pyplanemode.git denied to iquequeisso@gmail.com.
fatal: unable to access 'https://github.com/oleerik/pyplanemode/': The requested URL returned error: 403

**Comment by lillelilje** [comment]
Fixed, Try again now

**Comment by rsmaior** [comment]
rodrigo@3217 ~/pyplanemode $ git push origin master
Username for 'https://github.com': rudregues
Password for 'https://rudregues@github.com': 
Everything up-to-date

I think now it's gone!

**Comment by lillelilje** [comment]
git add *
git commit -m "New icons"
git push

**Comment by lillelilje** [comment]
Ah, that is beautiful! I like it!
